name: Deploy Solorder

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v2
            - name: Deploy site
              run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
